substitutions:
  bms2: "bms2"
  bms2_mac_address: C8:47:80:2B:83:85
  bms2_protocol_version: JK02_32S

ble_client:
  - mac_address: ${bms2_mac_address}
    id: "${bms2}_client"
    
jk_bms_ble:
  - ble_client_id: "${bms2}_client"
    protocol_version: ${bms2_protocol_version}
    throttle: 500ms
    id: "${bms2}_client_ble"

binary_sensor:
  - platform: jk_bms_ble
    jk_bms_ble_id: "${bms2}_client_ble"
    balancing:
      name: "${bms2} balancing"
    charging:
      name: "${bms2} charging"
    discharging:
      name: "${bms2} discharging"
    heating:
      name: "${bms2} heating"
    online_status:
      name: "${bms2} online status"

sensor:
  - platform: jk_bms_ble
    jk_bms_ble_id: "${bms2}_client_ble"
    min_cell_voltage:
      name: "${bms2} min cell voltage"
    max_cell_voltage:
      name: "${bms2} max cell voltage"
    min_voltage_cell:
      name: "${bms2} min voltage cell"
    max_voltage_cell:
      name: "${bms2} max voltage cell"
    delta_cell_voltage:
      name: "${bms2} delta cell voltage"
    average_cell_voltage:
      name: "${bms2} average cell voltage"
    cell_voltage_1:
      name: "${bms2} cell voltage 1"
    cell_voltage_2:
      name: "${bms2} cell voltage 2"
    cell_voltage_3:
      name: "${bms2} cell voltage 3"
    cell_voltage_4:
      name: "${bms2} cell voltage 4"
    cell_voltage_5:
      name: "${bms2} cell voltage 5"
    cell_voltage_6:
      name: "${bms2} cell voltage 6"
    cell_voltage_7:
      name: "${bms2} cell voltage 7"
    cell_voltage_8:
      name: "${bms2} cell voltage 8"
    cell_voltage_9:
      name: "${bms2} cell voltage 9"
    cell_voltage_10:
      name: "${bms2} cell voltage 10"
    cell_voltage_11:
      name: "${bms2} cell voltage 11"
    cell_voltage_12:
      name: "${bms2} cell voltage 12"
    cell_voltage_13:
      name: "${bms2} cell voltage 13"
    cell_voltage_14:
      name: "${bms2} cell voltage 14"
    cell_voltage_15:
      name: "${bms2} cell voltage 15"
    cell_voltage_16:
      name: "${bms2} cell voltage 16"
    cell_resistance_1:
      name: "${bms2} cell resistance 1"
    cell_resistance_2:
      name: "${bms2} cell resistance 2"
    cell_resistance_3:
      name: "${bms2} cell resistance 3"
    cell_resistance_4:
      name: "${bms2} cell resistance 4"
    cell_resistance_5:
      name: "${bms2} cell resistance 5"
    cell_resistance_6:
      name: "${bms2} cell resistance 6"
    cell_resistance_7:
      name: "${bms2} cell resistance 7"
    cell_resistance_8:
      name: "${bms2} cell resistance 8"
    cell_resistance_9:
      name: "${bms2} cell resistance 9"
    cell_resistance_10:
      name: "${bms2} cell resistance 10"
    cell_resistance_11:
      name: "${bms2} cell resistance 11"
    cell_resistance_12:
      name: "${bms2} cell resistance 12"
    cell_resistance_13:
      name: "${bms2} cell resistance 13"
    cell_resistance_14:
      name: "${bms2} cell resistance 14"
    cell_resistance_15:
      name: "${bms2} cell resistance 15"
    cell_resistance_16:
      name: "${bms2} cell resistance 16"
    total_voltage:
      name: "${bms2} total voltage"
    current:
      name: "${bms2} current"
    heating_current:
      name: "${bms2} heating current"
    power:
      name: "${bms2} power"
    charging_power:
      name: "${bms2} charging power"
    discharging_power:
      name: "${bms2} discharging power"
    temperature_sensor_1:
      name: "${bms2} temperature sensor 1"
    temperature_sensor_2:
      name: "${bms2} temperature sensor 2"
    temperature_sensor_3:
      name: "${bms2} temperature sensor 3"
    temperature_sensor_4:
      name: "${bms2} temperature sensor 4"
    power_tube_temperature:
      name: "${bms2} power tube temperature"
    balancing:
      name: "${bms2} balancing"
    state_of_charge:
      name: "${bms2} state of charge"
    capacity_remaining:
      name: "${bms2} capacity remaining"
    total_battery_capacity_setting:
      name: "${bms2} total battery capacity setting"
    charging_cycles:
      name: "${bms2} charging cycles"
    total_charging_cycle_capacity:
      name: "${bms2} total charging cycle capacity"
    total_runtime:
      name: "${bms2} total runtime"
    balancing_current:
      name: "${bms2} balancing current"


switch:
  - platform: jk_bms_ble
    jk_bms_ble_id: "${bms2}_client_ble"
    charging:
      name: "${bms2} charging"
    discharging:
      name: "${bms2} discharging"
    balancer:
      name: "${bms2} balancer"

  - platform: ble_client
    ble_client_id: "${bms2}_client"
    id: ${bms2}_ble_client_switch
    name: "${bms2} enable bluetooth connection"




text_sensor:
  - platform: jk_bms_ble
    jk_bms_ble_id: "${bms2}_client_ble"
    errors:
      name: "${bms2} errors"
    errors_bitmask_hex:
      name: "${bms2} errors bitmask hex"
    balancer_status:
      name: "${bms2} balancer status"
    total_runtime_formatted:
      name: "${bms2} total runtime formatted"
    software_version:
      name: "${bms2} software version"
    hardware_version:
      name: "${bms2} hardware version"